
from pathlib import Path
import argparse
import os
import subprocess

import nibabel as nib
from nilearn.masking import compute_epi_mask, intersect_masks


def run(command):
    print("\n$", " ".join(map(str, command)), flush=True)
    subprocess.run(command, check=True)


def build_glm_mask(subject):
    derivatives = Path("derivatives") / subject
    func_dir = derivatives / "func"
    anat_dir = derivatives / "anat"
    reg_dir = derivatives / "reg" / "mni"
    qc_dir = derivatives / "qc"
    qc_dir.mkdir(parents=True, exist_ok=True)

    bold_file = (
        func_dir
        / f"{subject}_task-heart_desc-stcMC_space-MNI_bold.nii.gz"
    )

    anat_mask = (
        qc_dir / f"{subject}_T1w_brain_mask_space-MNI.nii.gz"
    )

    func_mask_file = qc_dir / "bold_brain_mask_stcMC.nii.gz"
    final_mask_file = qc_dir / "glm_mask_final_subject_stcMC.nii.gz"

    # Use the anatomical mask generated by BET.
    t1_mask = anat_dir / f"{subject}_T1w_brain_mask.nii.gz"

    # Keep compatibility with the earlier sub-09210 filenames.
    if not t1_mask.is_file():
        alternative = anat_dir / f"{subject}_T1w_brain_f04R_mask.nii.gz"
        if alternative.is_file():
            t1_mask = alternative

    t1_to_mni = reg_dir / f"{subject}_T1w_to_MNI_affine.mat"

    fsl_dir = os.environ.get("FSLDIR")
    if not fsl_dir:
        raise RuntimeError("FSLDIR is not defined")

    template = (
        Path(fsl_dir) / "data/standard/MNI152_T1_2mm.nii.gz"
    )

    for path in (bold_file, t1_mask, t1_to_mni, template):
        if not path.is_file():
            raise FileNotFoundError(path)

    # 1. Transform the anatomical brain mask to MNI space.
    if anat_mask.is_file():
        print(f"Existing anatomical MNI mask: {anat_mask}")
    else:
        run([
            "flirt",
            "-in", str(t1_mask),
            "-ref", str(template),
            "-applyxfm",
            "-init", str(t1_to_mni),
            "-interp", "nearestneighbour",
            "-out", str(anat_mask),
        ])

    # 2. Estimate the functional mask.
    if func_mask_file.is_file():
        print(f"Existing functional mask: {func_mask_file}")
        func_mask = nib.load(func_mask_file)
    else:
        func_mask = compute_epi_mask(str(bold_file))
        func_mask.to_filename(func_mask_file)

    # 3. Intersect anatomical and functional masks.
    if final_mask_file.is_file():
        print(f"Existing final GLM mask: {final_mask_file}")
        final_mask = nib.load(final_mask_file)
    else:
        final_mask = intersect_masks(
            [str(anat_mask), str(func_mask_file)],
            threshold=1.0,
            connected=True,
        )
        final_mask.to_filename(final_mask_file)

    print(f"\nGLM mask complete: {subject}")
    print("Functional mask voxels:", int(func_mask.get_fdata().sum()))
    print("Final GLM mask voxels:", int(final_mask.get_fdata().sum()))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("subject")
    args = parser.parse_args()

    build_glm_mask(args.subject)
